# Generated by Django 5.2.7 on 2025-11-03 15:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlJourney', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningjourney',
            name='date_learned',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='hobby',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='learningjourney',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
